In [ ]:
# StudentName Khalida Afghan
#  Registration 24pwbcs1416
# Section E
# Assigned_DatasetName 49_warehouse_shipments

In [2]:
#import Libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [3]:
# Load your specific dataset
df=pd.read_csv("49_warehouse_shipments.csv")

In [4]:
# Look at the top 5 rows
df.head()

,ship_date,weight_kg,volume_cubic_m,distance_km,shipping_cost_usd,carrier,delivery_days,damaged,late_delivery,priority
0,2023-02-20 18:10:16.185973,10.65,0.296,518.6,18.83,UPS,1.0,0.0,0.0,Overnight
1,2022-09-07 11:06:21.283217,29.98,0.053,59.2,9.41,FEDEX,10.0,0.0,1.0,EXPRESS
2,2021-09-30 06:30:20.013396,2.93,0.066,575.2,7.83,USPS,4.0,0.0,1.0,Economy
3,2024-09-02 17:39:08.399895,1.16,0.250,1380.8,28.81,OnTrac,9.0,0.0,0.0,standard
4,2022-04-10 21:27:08.214436,17.44,0.118,115.0,5.30,fedex,NaN,0.0,0.0,NaN

In [5]:
# Print (number of rows, number of columns)
df.shape

(508, 10)

In [8]:
# Shows column names, blank counts, and data types
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 508 entries, 0 to 507
Data columns (total 10 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   ship_date          479 non-null    str
 1   weight_kg          495 non-null    float64
 2   volume_cubic_m     490 non-null    float64
 3   distance_km        490 non-null    float64
 4   shipping_cost_usd  478 non-null    float64
 5   carrier            486 non-null    str
 6   delivery_days      484 non-null    float64
 7   damaged            476 non-null    float64
 8   late_delivery      478 non-null    float64
 9   priority           483 non-null    str
dtypes: float64(7), str(3)
memory usage: 58.6 KB

In [7]:
# Summarizes the math (min, max, average) for number columns
df.describe()

,weight_kg,volume_cubic_m,distance_km,shipping_cost_usd,delivery_days,damaged,late_delivery
count,495.000000,490.000000,490.000000,478.000000,484.000000,476.000000,478.000000
mean,121.164626,2.474435,669.579592,79.040837,8.260331,0.042017,0.225941
std,999.123538,31.886108,3192.228918,557.598758,23.335309,0.200839,0.418639
min,-5.000000,-0.500000,-100.000000,-50.000000,-3.000000,0.000000,0.000000
25%,5.965000,0.147000,141.925000,4.542500,3.000000,0.000000,0.000000
50%,14.900000,0.331000,320.500000,13.845000,7.000000,0.000000,0.000000
75%,28.935000,0.612750,667.600000,23.752500,11.000000,0.000000,0.000000
max,10000.000000,500.000000,50000.000000,5031.940000,365.000000,1.000000,1.000000

In [9]:
# Pick a categorical column and count how many times each category appears
df['carrier'].value_counts()

carrier
FEDEX               72
USPS                71
fedex               62
DHL                 62
UPS                 60
Amazon Logistics    59
OnTrac              50
FedEx               50
Name: count, dtype: int64

In [11]:
# Group the data to find averages! (e.g., Average output by any categorical column)
df.groupby('carrier').mean(numeric_only=True)

,weight_kg,volume_cubic_m,distance_km,shipping_cost_usd,delivery_days,damaged,late_delivery
carrier,,,,,,,
Amazon Logistics,364.025172,9.240789,1239.672881,206.255926,6.508475,0.018182,0.196429
DHL,189.825763,0.410426,530.346667,97.077288,12.728814,0.016949,0.178571
FEDEX,18.911000,0.429042,436.475362,12.024559,7.628571,0.089552,0.257143
FedEx,19.928400,0.385319,453.522449,14.702766,7.434783,0.021739,0.204082
OnTrac,14.434490,0.424553,1545.908511,23.408163,5.934783,0.021739,0.183673
UPS,195.439123,0.488508,461.000000,195.271429,12.500000,0.036364,0.240741
USPS,168.089130,0.485338,493.257576,88.452794,6.647887,0.058824,0.287879
fedex,22.284590,8.833407,432.411290,17.474107,6.381818,0.033898,0.210526

In [13]:
# Count how many blanks are in each colum
df.isnull().sum()

ship_date            29
weight_kg            13
volume_cubic_m       18
distance_km          18
shipping_cost_usd    30
carrier              22
delivery_days        24
damaged              32
late_delivery        30
priority             25
dtype: int64

In [14]:
# Choice A: For text columns, fill blanks with the word "Unknown
df[['ship_date', 'carrier', 'priority']] = df[['ship_date', 'carrier', 'priority']].fillna('Unknown')

In [15]:
# Choice B: For number columns, fill blanks with the median (the middle number)
num_cols = df.select_dtypes(include='number').columns
df[num_cols] = df[num_cols].fillna(df[num_cols].median())

In [16]:
# Check for duplicates and drop them
df.duplicated().sum()
df=df.drop_duplicates()

In [17]:
# Make text lowercase and strip hidden spaces
df[['carrier', 'priority']] = df[['carrier', 'priority']].apply(lambda x: x.str.lower().str.strip())

In [18]:
# Example: Keep only rows where the Price is greater than 0
df = df[df['shipping_cost_usd'] > 0]

In [20]:
# Convert a text date into a real Python Datetime
df['ship_date'] = pd.to_datetime(df['ship_date'], errors='coerce')

In [21]:
# Create a brand new column that just contains the Month (1 through 12)
df['ship_month'] = df['ship_date'].dt.month

In [22]:
# Create a new column by dividing or multiplying two others
df['cost_per_kg'] = df['shipping_cost_usd'] / df['weight_kg']

In [23]:
# Convert text categories into separate columns of 1s and 0s (One-Hot Encoding)
df_encoded = pd.get_dummies(df, columns=['carrier', 'priority'], drop_first=True)

In [32]:
# Final statistical summary — compare this to your original Step 3 output
df.describe()

,ship_date,weight_kg,volume_cubic_m,distance_km,shipping_cost_usd,delivery_days,damaged,late_delivery,ship_month,cost_per_kg
count,402,424.000000,424.000000,424.000000,424.000000,424.000000,424.000000,424.000000,402.000000,424.000000
mean,2023-02-03 04:33:48.653054,139.727170,1.615745,724.387736,91.220259,8.582547,0.042453,0.209906,6.922886,inf
min,2021-01-02 17:43:08.468691,0.000000,-0.500000,-100.000000,0.040000,-3.000000,0.000000,0.000000,1.000000,0.002990
25%,2022-01-21 16:43:44.814574,7.402500,0.153750,157.750000,9.355000,3.000000,0.000000,0.000000,4.000000,0.551796
50%,2023-02-16 03:17:18.219999,17.325000,0.331000,323.600000,16.150000,7.000000,0.000000,0.000000,7.000000,0.861776
75%,2024-02-20 06:29:58.869765,31.055000,0.610250,687.125000,24.677500,11.000000,0.000000,0.000000,10.000000,1.772083
max,2024-12-26 19:43:30.920272,10000.000000,500.000000,50000.000000,5031.940000,365.000000,1.000000,1.000000,12.000000,inf
std,NaN,1078.585952,24.264377,3426.900845,591.010635,24.865934,0.201858,0.407722,3.289297,NaN

In [33]:
# Final null audit — all values should be 0

df.isnull().sum()

ship_date            22
weight_kg             0
volume_cubic_m        0
distance_km           0
shipping_cost_usd     0
carrier               0
delivery_days         0
damaged               0
late_delivery         0
priority              0
ship_month           22
cost_per_kg           0
dtype: int64

In [34]:
# Confirm data types of all columns after cleaning and feature engineeringkbdf.dtypes
df.dtypes

ship_date            datetime64[us]
weight_kg                   float64
volume_cubic_m              float64
distance_km                 float64
shipping_cost_usd           float64
carrier                         str
delivery_days               float64
damaged                     float64
late_delivery               float64
priority                        str
ship_month                  float64
cost_per_kg                 float64
dtype: object